// This file was automatically generated by lister-gen

package v1alpha1

// RedisClusterListerExpansion allows custom methods to be added to
// RedisClusterLister.
type RedisClusterListerExpansion interface{}

// RedisClusterNamespaceListerExpansion allows custom methods to be added to
// RedisClusterNamespaceLister.
type RedisClusterNamespaceListerExpansion interface{}
