// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/OlivierBoucher/redis-cluster-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RedisClusters returns a RedisClusterInformer.
	RedisClusters() RedisClusterInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// RedisClusters returns a RedisClusterInformer.
func (v *version) RedisClusters() RedisClusterInformer {
	return &redisClusterInformer{factory: v.SharedInformerFactory}
}
