// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/OlivierBoucher/redis-cluster-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RedisClusters returns a RedisClusterInformer.
	RedisClusters() RedisClusterInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// RedisClusters returns a RedisClusterInformer.
func (v *version) RedisClusters() RedisClusterInformer {
	return &redisClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
