// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	rediscluster_v1alpha1 "github.com/OlivierBoucher/redis-cluster-operator/pkg/apis/rediscluster/v1alpha1"
	versioned "github.com/OlivierBoucher/redis-cluster-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/OlivierBoucher/redis-cluster-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/OlivierBoucher/redis-cluster-operator/pkg/client/listers/rediscluster/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedisClusterInformer provides access to a shared informer and lister for
// RedisClusters.
type RedisClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RedisClusterLister
}

type redisClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewRedisClusterInformer constructs a new informer for RedisCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedisClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.RedisclusterV1alpha1().RedisClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.RedisclusterV1alpha1().RedisClusters(namespace).Watch(options)
			},
		},
		&rediscluster_v1alpha1.RedisCluster{},
		resyncPeriod,
		indexers,
	)
}

func defaultRedisClusterInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewRedisClusterInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *redisClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rediscluster_v1alpha1.RedisCluster{}, defaultRedisClusterInformer)
}

func (f *redisClusterInformer) Lister() v1alpha1.RedisClusterLister {
	return v1alpha1.NewRedisClusterLister(f.Informer().GetIndexer())
}
